map_string = '''CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTT
CCCCCCCCCCCCCC         C                  C          C        w    CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTTTTTT
CCCCCCCCCCCCCC         ◄┐                 C          C        www   CCCCCCCCCCCCCCCCCCCCCCCCCCCCCTTTTTTTTTTTTTT
CCCCCCCCCCCCCC         ◄┘                 ◄┐         ◄┐       wwww   CCCCCCCCCCCCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCC         C                  ◄┘         ◄│       wwwww  CCCCCCCCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCCCCCCCCCCC                  C          ◄│              CCCCCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCC                            C          ◄┘               CCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCC             ┌──┐          CC          C                CCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCCCCCCCCCCCCCC▼▼▼▼CCCCCCCCCCCC          C                CCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCC                            C          C                CCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCC  wwwwwwww                  C  wwwww   CCCCCCCC▲▲▲▲CCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCC  wwwwwwww                  C  wwwww   C       └──┘      TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCC                            CCCCCCCCCCCC                 TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC                          TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCC                                                         TTTTTTTTTTTTTTWWWWWwwwwwwwwwwwwwwwTTTTTT
CCCCCCCCCCCCCC                                                         TTTTTTTTTTTTTTWWWWWwwwwwwwwwwwwwwwTTTTTT
CCCCCCCCCCCCCC                                                         TTTTTTTTTTTTTTWWWWWwwwwwwwwwwwwwwwTTTTTT
CCCCCCCCCCCCCC                                                         TTTTTTTTTTTTTTWWWWWwwwwwwwwwwwwwwwTTTTTT
CCCCCCCCCCCCCC                                          wwwwwwwwwwwwwwwTTTTTTTTTTTTTTWWWWWwwwwwwwwwwwwwwwTTTTTT
CCCCCCCCCCCCCC               ┌───────────────┐          wwwwwwwwwwwwwwwTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTwwTTTTTTT
CCCCCCCCCCCCCC               │  N    #   S   │          wwwwwwwwwwwwwwwTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTwwTTTTTTT
CCCCCCCCCCCCCC               │###############│          wwwwwwwwwwwwwwwTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTwwTTTTTTT
CCCCCCCCCCCCCC               │               │          wwwwwwwwwwwwwwwTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTwwTTTTTTT
CCCCCCCCCCCCCC               │               │          wwwwwwwwwwwwwwwTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTwwTTTTTTT
CCCCCCCCCCCCCC               └─pp────────────┘          wwwwwwwwwwwwwwwTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTwwTTTTTTT
CCCCCCCCCCCCCC                 pp Poke'center                   wwwwwwwTTTTTTTTTTTTTTwwwwwwwwwwwwwwwTTwwTTTTTTT
CCCCCCCCCCCCCC                 pp                               wwwwwwwTTTTTTTTTTTTTTwwwwwwwwwwwwwwwTTwwTTTTTTT
CCCCCCCCCCCCCC                 pp                               wwwwwwwTTTTTTTTTTTTTTwwwwwwwwwwwwwwwTTwwTTTTTTT
CCCCCCCCCCCCCC                 pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppwwwwwwwwwTTTTTT
CCCCCCCCCCCCCC                 pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppwwwwwwwwwTTTTTT
CCCCCCCCCCCCCC                                                  wwwwwwwTTTTTTTTTTTTTTwwwwwwwwwwwwwwwTTTTTTTTTTT
CCCCCCCCCCCCCC                                                  wwwwwwwTTTTTTTTTTTTTTwwwwwwwwwwwwwwwTTTTTTTTTTT
CCCCCCCCCCCCCC                                                  wwwwwwwTTTTTTTTTTTTTTwwwwwwwwwwwwwwwTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW                                TTTTTTTTTTTTTTwwwwwwwwwwwwwwwTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW                                TTTTTTTTTTTTTTTTTTwwTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW                                TTTTTTTTTTTTTTTTTTwwTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW    wwwwwwwww                   TTTTTTTTTTTTTTTTTTwwTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW    wwwwwwwww                   TTTTTTTTTTTTTTTTTTwwTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW    wwwwwwwww                   TTTTTTTTTTTTTTTTTTwwTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTwwTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTwwTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTwwwwwwwwwwTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTwwwwwwwwwwTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTTTwwwwwwwwTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTTTwwwwwwwwTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTTTwwwwwwwwTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
CCCCCCCCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT'''